openapi: "3.0.0"
info:
  title: PetCare Service
  description: Implementation of PetCare
  version: 0.1.0
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Limit of items in list
          required: true
          schema:
            type: integer
            format: int64
            example: 5
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
        400:
          description: Bad Request
        404:
          description: Not Found

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - breed
        - owner
      properties:
        id:
          type: integer
          example: 1
          format: int64
        name:
          type: string
          example: "Aron"
        breed:
          $ref: "#/components/schemas/Breed"
        owner:
          $ref: "#/components/schemas/Owner"
    Owner:
      type: object
      required:
        - id
        - lastName
        - firstName
      properties:
        id:
          type: integer
          example: 1
          format: int64
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
    Breed:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
          format: int64
        name:
          type: string
          example: "rottweiler"
        description:
          example: "Dog breed black and brown, seems vicious but are the best cuddlers"
          type: string
    Treatment:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
          format: int64
        name:
          type: string
          example: "Returning to normal nails"
        description:
          example: "Long treatment of cutting nails little by little"
          type: string
    Session:
      type: object
      required:
        - id
        - pet
        - treatment
        - sessionDate
      properties:
        id:
          type: integer
          example: 1
          format: int64
        sessionDate:
          type: string
          example: "2022-11-16T20:15:23"
          format: date-time
        pet:
          $ref: "#/components/schemas/Pet"
        treatment:
          $ref: "#/components/schemas/Treatment"
    Payment:
      type: object
      required:
        - id
        - session
        - owner
        - paymentDate
      properties:
        id:
          type: integer
          example: 1
          format: int64
        session:
          $ref: "#/components/schemas/Session"
        owner:
          $ref: "#/components/schemas/Owner"
        paymentDate:
          type: string
          example: "2022-11-16T22:20:13"
          format: date-time